import { Lead, MetricCard } from "./types";

// Mock Lead Data
export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    company: "Tesla Inc.",
    email: "sarah.j@tesla.com",
    phone: "+1 (555) 123-4567",
    value: 125000,
    status: "qualified",
    priority: "high",
    assignedTo: "John Doe",
    assignedToAvatar: "JD",
    createdAt: new Date("2024-11-01"),
    lastActivity: new Date("2024-11-17"),
    notes: "Interested in enterprise solution"
  },
  {
    id: "2",
    name: "Michael Chen",
    company: "SpaceX",
    email: "m.chen@spacex.com",
    phone: "+1 (555) 234-5678",
    value: 250000,
    status: "negotiation",
    priority: "high",
    assignedTo: "Jane Smith",
    assignedToAvatar: "JS",
    createdAt: new Date("2024-10-15"),
    lastActivity: new Date("2024-11-18"),
    notes: "Requires custom integration"
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    company: "Amazon Web Services",
    email: "e.rodriguez@aws.com",
    phone: "+1 (555) 345-6789",
    value: 180000,
    status: "proposal",
    priority: "high",
    assignedTo: "John Doe",
    assignedToAvatar: "JD",
    createdAt: new Date("2024-11-05"),
    lastActivity: new Date("2024-11-16"),
    notes: "Waiting for proposal review"
  },
  {
    id: "4",
    name: "David Kim",
    company: "Microsoft",
    email: "d.kim@microsoft.com",
    phone: "+1 (555) 456-7890",
    value: 95000,
    status: "contacted",
    priority: "medium",
    assignedTo: "Jane Smith",
    assignedToAvatar: "JS",
    createdAt: new Date("2024-11-10"),
    lastActivity: new Date("2024-11-15"),
  },
  {
    id: "5",
    name: "Lisa Anderson",
    company: "Google",
    email: "l.anderson@google.com",
    phone: "+1 (555) 567-8901",
    value: 320000,
    status: "qualified",
    priority: "high",
    assignedTo: "Mike Wilson",
    assignedToAvatar: "MW",
    createdAt: new Date("2024-10-28"),
    lastActivity: new Date("2024-11-18"),
    notes: "Key decision maker identified"
  },
  {
    id: "6",
    name: "Robert Taylor",
    company: "Salesforce",
    email: "r.taylor@salesforce.com",
    phone: "+1 (555) 678-9012",
    value: 65000,
    status: "new",
    priority: "medium",
    assignedTo: "John Doe",
    assignedToAvatar: "JD",
    createdAt: new Date("2024-11-18"),
    lastActivity: new Date("2024-11-18"),
  },
  {
    id: "7",
    name: "Jennifer Martinez",
    company: "Oracle",
    email: "j.martinez@oracle.com",
    phone: "+1 (555) 789-0123",
    value: 145000,
    status: "proposal",
    priority: "high",
    assignedTo: "Jane Smith",
    assignedToAvatar: "JS",
    createdAt: new Date("2024-11-03"),
    lastActivity: new Date("2024-11-17"),
    notes: "Technical demo scheduled"
  },
  {
    id: "8",
    name: "James Wilson",
    company: "IBM",
    email: "j.wilson@ibm.com",
    phone: "+1 (555) 890-1234",
    value: 78000,
    status: "new",
    priority: "low",
    assignedTo: "Mike Wilson",
    assignedToAvatar: "MW",
    createdAt: new Date("2024-11-17"),
    lastActivity: new Date("2024-11-17"),
  },
  {
    id: "9",
    name: "Amanda Brown",
    company: "Adobe",
    email: "a.brown@adobe.com",
    phone: "+1 (555) 901-2345",
    value: 210000,
    status: "negotiation",
    priority: "high",
    assignedTo: "John Doe",
    assignedToAvatar: "JD",
    createdAt: new Date("2024-10-20"),
    lastActivity: new Date("2024-11-18"),
    notes: "Final pricing discussion"
  },
  {
    id: "10",
    name: "Christopher Davis",
    company: "Netflix",
    email: "c.davis@netflix.com",
    phone: "+1 (555) 012-3456",
    value: 155000,
    status: "contacted",
    priority: "medium",
    assignedTo: "Jane Smith",
    assignedToAvatar: "JS",
    createdAt: new Date("2024-11-12"),
    lastActivity: new Date("2024-11-14"),
  },
];

// Mock Metrics Data
export const mockMetrics: MetricCard[] = [
  {
    id: "1",
    title: "Total Leads",
    value: mockLeads.length,
    change: 12,
    changeLabel: "vs last month",
    icon: "users",
    trend: "up"
  },
  {
    id: "2",
    title: "Active Opportunities",
    value: mockLeads.filter(l =>
      ["qualified", "proposal", "negotiation"].includes(l.status)
    ).length,
    change: 8,
    changeLabel: "vs last week",
    icon: "target",
    trend: "up"
  },
  {
    id: "3",
    title: "Conversion Rate",
    value: "24.5%",
    change: -3.2,
    changeLabel: "vs last month",
    icon: "trendingUp",
    trend: "down"
  },
  {
    id: "4",
    title: "Revenue Forecast",
    value: `$${(mockLeads.reduce((sum, lead) => sum + lead.value, 0) / 1000).toFixed(0)}K`,
    change: 15.8,
    changeLabel: "vs last quarter",
    icon: "dollarSign",
    trend: "up"
  }
];
